export PROJECT = test_anytransceiver
export BOARD ?= native
export RIOTBASE ?= $(CURDIR)/../..
QUIET ?= 1

USEMODULE += auto_init
USEMODULE += anytransceiver
USEMODULE += hwtimer

include $(RIOTBASE)/Makefile.include
