ifneq (,$(filter anytransceiver,$(USEMODULE)))
	ifeq (,$(filter cc110x_ng,$(USEMODULE)))
		USEMODULE += cc110x_ng
	endif
	ifeq (,$(filter transceiver,$(USEMODULE)))
		USEMODULE += transceiver
	endif
endif
