ifneq (,$(filter anytransceiver,$(USEMODULE)))
	ifeq (,$(filter nativenet,$(USEMODULE)))
		USEMODULE += nativenet
	endif
	ifeq (,$(filter transceiver,$(USEMODULE)))
		USEMODULE += transceiver
	endif
endif
